### ISSUE TITLE
Update psalm and php-cs-fixer

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-plugin-ci#17]
Current versions of psalm and php-cs-fixer are really outdated. I tried updating them at #16 , together with other components, but there were a number of errors detected to fix, so I decided to split that to this issue.

Target versions must work for PHP 7.0 to 7.4 (right now).

**Comment by stronk7** [comment]
This is also needed to get #6 solved properly as far as current versions are not PHP 7.4 compliant.

**Comment by kabalin** [comment]
Just to note that psalm was updated to 3.18.2 in #64. The current one is 4.x which has got php7.3 as minimum requirement, thus we are still in 3.x. When upgrading to 4.x consider:
* having psalm as composer dependency (rather than fetching using curl, see Makefile).
* Review psalm.xml carefully, especially cases when whole file is ignored for some typo of error, alternative could be fixing or using inline `psalm-supress` statement.
