### ISSUE TITLE
PHPDoc Checker: Don't fail when only warnings are emitted

### ISSUE THREAD

**Issue by MHajoha** [moodlehq/moodle-plugin-ci#186]
moodle-local_moodlecheck distinguishes between warnings and errors. Ideally, moodle-plugin-ci should not fail when only warnings (such as in moodlehq/moodle-local_moodlecheck#82) are emitted. Moodlecheck currently outputs the severity only in xml format, which would need to be changed to make this possible. Alternatively, we could consume moodlecheck's XML output or modify moodlecheck to determine the sensible exit code by itself.

**Comment by kabalin** [comment]
Ideally, phpdoc checks need to be converted to phpcs sniffs one day (i.e. https://tracker.moodle.org/browse/CONTRIB-4165 needs to be re-evaluated).

**Comment by stronk7** [comment]
While moving all current local_moodlecheck stuff to moodle-cs (PHP_CodeSniffer) is a goal that we must not ignore (at all), because it's easier to maintain, already has lots of Sniffs covering 85% of usual cases...

... thinking about this, my opinion is that it would be great to have the {{max-warnings}} option into the {{phpdoc}} command, offering a behavior similar to the codechecker one, aka.

1. (Change of behaviour). Without {{max-warnings}} specified (aka, -1), exit status changes to 0 (if there aren't errors, of course).
2. With {{max-warnings}} specified, exit status changes to zero if under the threshold (if there aren't errors, of course).

I think it's not super hard to add support for that option and, once the command has been executed ([src/Command/PHPDocCommand.php](https://github.com/moodlehq/moodle-plugin-ci/blob/master/src/Command/PHPDocCommand.php#L65-L85)) we can more or less easily count the number of errors, the number of warnings, make some simple calculations and alter the exit status. Not exactly the same, but very similar to what `src/Command/CodeCheckerCommand.php` does.

(Note that we can play with the output format - maybe, just talking from memory, to generate XML for easier parsing / counting errors and warnings). Maybe not!

Ciao :-)

PS: This would keep moodlecheck in pair with codechecker (feature wise), so whenever it's gradually (or completely) moved to the new checker... behaviour won't change.

**Comment by MHajoha** [comment]
A `max-warnings` option sounds great! :+1: Although, wouldn't it make more sense to add it directly to moodlecheck's CLI and remove the need for moodle-plugin-ci to parse the output altogether?

> While moving all current local_moodlecheck stuff to moodle-cs (PHP_CodeSniffer) is a goal that we must not ignore (at all)

So this has been reconsidered since [CONTRIB-4165](https://tracker.moodle.org/browse/CONTRIB-4165)? 

I feel that moodlehq/moodle-local_moodlecheck#82 was an easy and quick improvement, but it doesn't change the fact that moodlecheck emits a ton of false positives for overridden methods. From what I can see, CodeSniffer isn't any more suited to checking whether a method does override another, which would require resolving superclasses. Has it ever been considered to integrate with phpstan or Psalm, which (I'm guessing) already do this?

**Comment by stronk7** [comment]
Closing this because of #228 now landed upstream. A release (v4.1.0) containing it will come soon...
