### ISSUE TITLE
Node 16 from 12

### ISSUE THREAD

**Issue by gjb2048** [moodlehq/moodle-plugin-ci#187]
Hello,

I was getting a notice about Node 16 to 12 -> https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ - and solved this by changing:

actions/checkout@v2

to

actions/checkout@v3

But clearly the example needs to update :)

**Comment by stronk7** [comment]
Aha, good point @gjb2048 . I've confirmed that we are getting the warnings also in core (fun because, I've not had any failure recently, so I had not visited the GHA UI since time ago):

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/setup-node, actions/checkout
```

So not only moodle-plugin-ci is affected but surely other repos too. Will review all them soon (including this) and proceed to bump the needed versions.

Ciao :-)

**Comment by stronk7** [comment]
Cross-linking with [MDL-75983](https://tracker.moodle.org/browse/MDL-75983), that is the Tracker issue where we'll review core and tools (this included).

**Comment by stronk7** [comment]
Have just created #190 to change all occurrences and recommend everybody to bump their workflows to the new one.

Ciao :-)
