### ISSUE TITLE
Switch from the abandoned jakub-onderka/php-parallel-lint to php-parallel-lint/php-parallel-lint

### ISSUE THREAD

**Issue by mark-webster-catalyst** [moodlehq/moodle-plugin-ci#230]
As noted on https://github.com/JakubOnderka/PHP-Parallel-Lint that project has been abandoned and it is recommended to switch to using https://github.com/php-parallel-lint/PHP-Parallel-Lint.

**Comment by stronk7** [comment]
Hi @mark-webster-catalyst ,

I'm a little bit confused here. Unless I'm wrong we are using the `php-parallel-lint/php-parallel-lint` package since the night of the times (2020). See this commit: https://github.com/moodlehq/moodle-plugin-ci/commit/040ffa3053bf2aa4d6644a6b54542898c51e717b

So both the 3.x and 4.x versions of moodle-plugin-ci are using it.

I'm closing this now. If I'm missing something, please tell. Thanks for the report.

**Comment by mark-webster-catalyst** [comment]
Ahh I see. I was reading the code and saw mentions of JakubOnderka in the `use` statements, didn't get so far as checking the composer file. Assuming they still allow inclusion via the old name for backwards compatibility?
