### ISSUE TITLE
Remove Copy/Paste Detector integration

### ISSUE THREAD

**Issue by stopfstedt** [moodlehq/moodle-plugin-ci#262]
during `composer install`, i'm seeing this warning:

```
Package sebastian/phpcpd is abandoned, you should avoid using it. No replacement was suggested.
```

and true enough, the code repo has been flagged as abandoned. https://github.com/sebastianbergmann/phpcpd

i'm proposing the complete removal of this integration.

**Comment by stronk7** [comment]
Hi @stopfstedt ,

yeah, we were aware about the removal. Also, we have been monitoring how forks (of phpcpd) are evolving, with a couple of them that "may" be interesting to switch to.

Thanks for creating this and #263, we'll analyse this soon, because one of the things we need to carefully consider is how the (potential) removal is going to affect to all the plugins out there that are running the `phpcpd` command, maybe requiring it to stay, but warning about the deprecation of the command, instead of a sudden deletion.

Let's see how everything evolves... I'll keep both this and the PR open as a reminder... hope we can come with a decision soon (switch, deprecate, remove...).

Ciao :-)

**Comment by stopfstedt** [comment]
@stronk7 thanks for the review.
i agree with your concerns - sudden removal might be a bit jarring.

i started with a new PR that deprecates this feature as an intermediary solution.

**Comment by stronk7** [comment]
Now that the deprecation has landed as part of #264 , I'll keep this open for whenever we make the next major version (5.0.0). Then, the `phphpd` command will be completely removed.

Ciao :-)

**Comment by jrchamp** [comment]
@stronk7 Now that `phpcpd` is deprecated, it seems like it should be removed from the sample workflow files. I understand that complete removal should happen in a major version (because it breaks backward compatibility), but the sample workflow files are more like "suggested best practices", which should probably be updated to stop using deprecated commands. With that said, whatever you decide, I'm fine either way.

**Comment by stronk7** [comment]
> it seems like it should be removed from the sample workflow files.

Agreed, I've created #290 to remove it from dist and "explain" docs. Good idea!

Ciao :-)

**Comment by stronk7** [comment]
Ok, I' think that this can be considered done.

The complete removal has happened as part of the https://github.com/moodlehq/moodle-plugin-ci/milestone/1 , and now it's part of the https://github.com/moodlehq/moodle-plugin-ci/tree/wip_v5 branch.

Ciao :-)
