### ISSUE TITLE
Problems trying to use GHA against 34_STABLE and 36_STABLE

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-plugin-ci#79]
Detected when using the suggested [GHA file with local_codechecker](https://github.com/moodlehq/moodle-local_codechecker/pull/131).

I've created [this branch that reproduces the problems](https://github.com/stronk7/moodle-plugin-ci/compare/verify_34_and_36_failures~1...verify_34_and_36_failures) within moodle-plugin-ci own tests:

https://github.com/stronk7/moodle-plugin-ci/actions/runs/523600001

Summary of mini-research performed till now follows:

> Adding support for GHA in local_codechecker, it has been detected.
> that the builds for 34 and 36 stable branches are failing badly.
> 
> But the Travis conunterparts are passing without a problem.
> 
> See:
> 
> - GHA failing: https://github.com/stronk7/moodle-local_codechecker/actions/runs/522315954
> - Travis passing: https://travis-ci.com/github/moodlehq/moodle-local_codechecker/builds/215355630
> 
> For now, the mini-research performed points to:
> 
> - 34_STABLE: That branch misses .nvmrc file and when that happens.
> moodle-plugin-ci does create it, pointing to lts/carbon. Travis
> seems to be getting that lts/carbon perfectly, but GHA is not,
> so it tries installing latest/current node version and that fails.
> 
> - 36_STABLE: Not sure why but it's trying to download an incorrect
> node-sass binary. As far as the download fails... then tries to
> build it locally and that also fails. It works ok (correct download)
> both with travis, real linux, mac osx... not sure why not with GHA
> (I've seen "System Linux 5.4.0-1036-azure" is reported elsewhere in
> the logs... not sure if that may be the cause).

Maybe both are because of problems the the node / nvm stuff, or we are
executing something out of order, don't know. But certainly... the problem
with those 2 branches can be reproduced consistently. And they work
without a problem with Travis.

Ciao :-)

**Comment by kabalin** [comment]
This is failing because nvm installation does not take place. You can see that at [this line](https://github.com/stronk7/moodle-plugin-ci/runs/1797874736?check_suite_focus=true#step:6:79), `nvm` installation should take place just before global dependencies  are installed, and it is not there (that is the case for any other CI runs also). It is a shame I did not investigate it properly after removing `setup-node` step.

**There are two problems really:**

1.  GHA shell is a bit unique - "[Commands run using non-login shells by default.](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun)", this results that `NVM_DIR` is not available by default for the `run` process.
2. In [VendorInstaller](https://github.com/moodlehq/moodle-plugin-ci/blob/master/src/Installer/VendorInstaller.php#L105) we check `NNM_BIN`. Even if we do 1 right, so that login shell is used and we have `NVM_DIR` available, `NVM_BIN` is not defined there (perhaps a specific of nvm installation in HGA).

**How to fix:**

1. There are two options here, either to define `NVM_DIR` at initialise step (see example below) or add `shell: bash -l {0}` to `moodle-plugin-ci install` step.
2. `NVM_BIN` was added "just to be sure", it is not used anywhere apart of that check, it is totally sufficient to check `NVM_DIR` only.

Here is the same `verify_34_and_36_failures` branch with a patch: https://github.com/kabalin/moodle-plugin-ci/commit/786751d638996fbba1d05c80f967250df0b4959a

You can see, it passes (well, 34-7.2 fails but for different reason)
https://github.com/kabalin/moodle-plugin-ci/actions/runs/528876252

And you can see that nvm installation takes place:
https://github.com/kabalin/moodle-plugin-ci/runs/1809887687?check_suite_focus=true#step:6:71

PS Used this thread to figure the problem: https://github.com/actions/virtual-environments/issues/4#issuecomment-601146989

**Comment by stronk7** [comment]
Yay, great research!
