### ISSUE TITLE
Github workflows is not using the default ansi output setting

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-plugin-ci#91]
Locally or using Travis, the output is colored.  In Github workflows one needs to add the parameter --ansi to see some colors.

Perhaps this can be a sign that other default parameters are ignored in Github workflows.

**Comment by stronk7** [comment]
Yeah,

I've seen various issues, where different tools have to "force" the colorised output, each one using its own witch (`--ansi`, `--color` ...). For example https://github.community/t/ansi-color-output-in-webview/17621

It seems that there is something in the default environment causing the tools not to detect that color is supported (because, in fact, it is!).

Have tried finding some issue reporting this but have failed to find any, so far.

I'll keep this open... but my initial impression is that it's something in GHA env sort of "tricking" the tools.

Ciao :-)

**Comment by stronk7** [comment]
Just found this https://github.com/actions/runner/issues/241, pretty old and open that comes to confirm that GHA doesn't provide a tty, and that's is what most tools use to decide if output supports colors or no.

There are some tricks to get that working, like creating a new shell before the command, or as you commented, to "force" the colors to be output (with each tool own switch).

Whoever wants to go adding the "force" colors using each tool own switch, that's ok

But I don't think we should change anything to apply for that by default, that would break uses that want to send results to file, or pipe, or grep...

**Comment by kabalin** [comment]
> But I don't think we should change anything to apply for that by default, that would break uses that want to send results to file, or pipe, or grep...

I agree. In fact commands run using non-login shell by default in GHA, might be partly related to colours issue.

**Comment by stronk7** [comment]
Thanks @ewallah , per the comments above I'm closing this now.

Ciao :-)
